### PR TITLE
Check if element is of type "custom", then stop with sub-child select…

### PR DESCRIPTION
**Pull request by ifekonja**
…ion.

### CODE REVIEW

**Comment by jogibear9988** [comment]
Can you add a sample HTML you use your changes in?

I look how we could add this.

**Comment by ifekonja** [comment]
I use JavaScript "createElement('custom-eco-fb')" , not HTML
and want wo void childs to be selected
Same valids for "static" selector, so it cannot be selected, since it is controlled by my platform

**Comment by ifekonja** [comment]
But I didnt change it properly, since still NULL designItem are coming and Objects are no more selectable at all, I dont know what I did wrong

**Comment by ifekonja** [comment]
And shadow selection frames are remaining on the sheet (from original position)

**Comment by jogibear9988** [comment]
are you trying something like this:

      <div>
          <custom-aaa><span>aaa</span><span>bbb</span></custom-aaa>
      </div>

but here your are not able to select all components inside of "custom...."
It should behave like if it is a custom HTML element?

I can look how this would be possible.

But you know (if you want this) that it already works like this:

      <div>
          <custom-aaa style="position:absolute;left:0px;top:3px;">
              <template shadowrootmode="open">
                  <span>aaa</span>
                  <span>bbb</span>
              </template>
          </custom-aaa>
      </div>

**Comment by ifekonja** [comment]
It would be nice to get the events "forwarded" in bithe cases (locked and custom), so I could perform my own reactions. But I dont know how...over platform callback or over "template-class".... do you have any example of template-class, I would like to use it (in custom-menu and connected to events)

**Comment by jogibear9988** [comment]
I (again) don't understand. Maybe describe your case better then I can help you.
What are you trying to build? Wich events you like forwarded? I don't get it.

**Comment by ifekonja** [comment]
I have to get "mouse move" to my handler; it is ok that it is moved, but I have to react to to those events in my platform.
So I am missing some art of "extended" callback (over template?).
So PointTool would send mouse events also to template-event handlers

**Comment by jogibear9988** [comment]
I still don't get it. Could you not describe your complete usecase a little bit more.

**Comment by jogibear9988** [comment]
I close, as the issue could be resolved via declaritive shadowdom, if not we could create a extension but not like this with hardcoded  values

**Pull request closed without merging**
