### PR TITLE
Implement jump to feature #209 --> added jump to into the contextmenu.

### PR DESCRIPTION
**Pull request by cedricfranke28**

### CODE REVIEW

**Comment by cedricfranke28** [comment]
Further information is in the ticket.

**Comment by jogibear9988** [comment]
do we need a new api for this? could we not use zoomToPoint with the current zoom factor?

**Comment by cedricfranke28** [comment]
I thought the jump to feature should be without an zoomfaktor. Just middle the specific element in the designer.

**Comment by cedricfranke28** [comment]
I moved the jumpt to feature inside the zoom to api. It works identical.

**Pull request merged**
