### PR TITLE
button-icon

### PR DESCRIPTION
**Pull request by ifekonja**
Support for button-icon in menu list

### CODE REVIEW

**Comment by jogibear9988** [comment]
For what is iconPath used

**Comment by ifekonja** [comment]
> For what is iconPath used

1) for JSON entry in elements-html:  "iconPath": "images/traffic1.png"
2) together with "projectPath" in paletteView.loadControls(serviceContainer, serviceContainer.elementsServices, web_project_path);
3) it will be used in paletteElements.ts code as default html: (not yet commit-ed ,,, should I ?)
     if( elementDefintion.iconPath && !elementDefintion.displayHtml && projectPath ) // IZI
      {
        let icon_path= projectPath+ elementDefintion.iconPath;
        let html=
          '<table><tr>'
          '<td align="left" valign="middle" style="width:20px;"></td>' +
          '<td align="left" >' + elementDefintion.tag + '</td>' + 
		  '</tr></table>\n';
				
		elementDefintion.displayHtml = html; // IZI
      }
      if (elementDefintion.displayHtml) // IZI 
      {
		  button.innerHTML = elementDefintion.displayHtml; // IZI 
      }

**Comment by ifekonja** [comment]
Actual HTML code dissapered in "comment" after clicking the button (GitHub misinterprets it)
Should I commit also this table+tr+td code sequence for default iconPath behaviour?

**Comment by jogibear9988** [comment]
i still don't understand what the iconPath is used for (as I can not see your code).

If you intend your samle code by 4 spaces, github will show it correctly.

**Comment by jogibear9988** [comment]
I don't see if we should add this icon path behavior. Why not use the "displayHtml" with this code....
But the iconPath maybe could also be used in the treeViewVersion of the Elements Palette...

Need to think about it, will look for it tomorrow

**Comment by ifekonja** [comment]
I have adapted/commited "default iconPath+projectPath -> displayHtml behaviour

**Comment by ifekonja** [comment]
In the AddOn Example I use following modification:
const web_file_path= original_url.href.replace("out/webview/designer.js","");
var web_project_path= web_file_path + "project/";
let elements_native_json = await import(web_project_path+'elements-native.json', { assert: { type: 'json' } })
paletteView.loadControls(serviceContainer, serviceContainer.elementsServices, web_project_path);

It works fine
Should I update also AddOn repository?

**Comment by jogibear9988** [comment]
I've changed the code a little bit and pushed it

**Comment by jogibear9988** [comment]
yeah create a pull for the addon, update also the npms

**Pull request closed without merging**
